### ISSUE TITLE
New branded App MoH Niger - "Alerte Niger"

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-android#206]
Ticket to keep track of the changes and steps needed to release the new branded App "Alerte Niger" from _MoH Niger_.

### Tasks

- [x] PR https://github.com/medic/cht-android/pull/203 with the branded app configuration (@RishJ08)
- [x] Merge PR (@mrsarm) → waiting merge of this other [PR](https://github.com/medic/cht-android/pull/202) needed to make CI woks again.
- [x] Setup Google account that is going to be used to publish the app (@kitsao)
- [x] New PR with signing keys ( @RishJ08 @mrsarm ) → waiting workflow PR for publishing
- [x] Release cht-android v0.9.0 with the new flavor ( @mrsarm )
- [x] Publish it in the Play Store ( @RishJ08 @kitsao) → Published in the Play Store v0.9.0 release in the "Internal" testing channel. Now Apps Services need to continue the setup in order to promote it to "Production".

**Comment by Fatoufall** [comment]
[Alert Niger Mobile App playstore .docx](https://github.com/medic/cht-android/files/6970264/Alert.Niger.Mobile.App.playstore.docx)

**Comment by mrsarm** [comment]
[Alert.Niger-Media.zip](https://github.com/medic/cht-android/files/6971003/Alert.Niger-Media.zip)

:point_up: here are the media files from the doc file above.

**Comment by mrsarm** [comment]
@kitsao , from @Fatoufall document, here are the new assets for the Play Store:

Short description:

> Application pour la notification rapide des maladies à potentiel épidémique.

New 512x512px App icon:

![alerte_niger_icon_512px](https://user-images.githubusercontent.com/1608415/129485219-60a40b18-e2db-4f56-b412-949121110f78.png)

New 1024x500px background image:

![alerte_niger_background_1024x500px](https://user-images.githubusercontent.com/1608415/129485253-53b8bc10-0923-4b8d-95bd-8a26c33889fc.jpg)

**Comment by mrsarm** [comment]
The App was published in the Play Store, release v0.9.0 in the "Internal" testing channel.

Now Apps Services need to continue the setup in order to promote it to "Production", so closing here the ticket but fill free to reopen if there is something that needs to be fixed by the Product team.

**Comment by kitsao** [comment]
Roll out to production is in progress.
