### ISSUE TITLE
Update list of CHT dev instances and reference apps

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-android#225]
The list of reference apps and CHT instances is outdated.

### Tasks

- [ ] Disable Simprints for now (integration is not working, and dev environment down):
  - [x] Disable the app in the Play Store
  - [ ] Disable the flavor from the list of apps built when releasing
  - [ ] Remove from the list of reference apps in the README
- [ ] Add https://demo-cht.dev.medicmobile.org/ :
  - [ ] Add it to the list of CHT instances in the Unbranded flavor
  - [ ] Re-enable the Demo App (`medicmobiledemo` flavor) but pointing to this instance instead:
    - [ ] In the code re-enable it in the releases in CI, and change the URL
    - [ ] Add it again in the list of reference apps in the README
    - [ ] Re-enable it in the Play Store: in order to publish the latest version we have to release v0.10.0-1
