### ISSUE TITLE
New branded App NSSD MoH Nepal - "CHIS"

### ISSUE THREAD

**Issue by binokaryg** [medic/cht-android#231]
Ticket to keep track of the changes and steps needed to release the new branded App "CHIS" from NSSD, MoH Nepal.

### Tasks
- [x]  PR added chis_ne flavor #229 with the branded app configuration (@RishJ08)
- [x]  Merge PR (@mrsarm)
- [x]  Setup Google account that is going to be used to publish the app
- [x]  PR with signing keys
- [x]  Release cht-android with the new flavor ( @mrsarm )
- [ ]  Publish it in the Play Store

**Comment by binokaryg** [comment]
Play store has rejected the app and we need the official letter from the Government of Nepal. This has been communicated to the PM [on Jan 13, 2022](https://medic.slack.com/archives/C024SEFFG2K/p1642067366006400).

**Comment by garethbowen** [comment]
@binokaryg Can this be closed as complete now?

**Comment by binokaryg** [comment]
> @binokaryg Can this be closed as complete now?

Yes.
